[workspace]
resolver = "2"
members = [
    "crates/cli",
    "crates/ir",
    "crates/codegen",
    "crates/parser",
    "crates/filecheck",
    "crates/triple",
    "crates/macros",
    "crates/interpreter",
    "crates/verifier",
]

[workspace.package]
edition = "2024"

[patch.crates-io]
naga = { git = "https://github.com/micahscopes/wgpu", rev = "854ed576fa186d19b9f7d5a5bb5a1f2fa533dde1" }
